const search=document.querySelector('#game-search'),results=document.querySelector('#search-results');let current=null;
const esc=s=>String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const date=s=>new Intl.DateTimeFormat(undefined,{day:'numeric',month:'short',year:'numeric'}).format(new Date(s));
async function api(url){const r=await fetch(url),data=await r.json();if(!r.ok)throw Error(data.error||'Request failed');return data;}
function show(items){results.innerHTML=items.map(g=>`<button class="result" data-appid="${g.appid}"><img src="${esc(g.image)}" alt=""><div><b>${esc(g.name)}</b><small>Steam · live reviews & updates</small></div></button>`).join('');}
let wait;search.addEventListener('input',()=>{clearTimeout(wait);const q=search.value.trim();if(q.length<2){results.innerHTML='';return;}wait=setTimeout(async()=>{try{show(await api(`/api/search?q=${encodeURIComponent(q)}`));}catch(e){results.innerHTML=`<div class="result error">${esc(e.message)}</div>`;}},250);});
results.addEventListener('click',e=>{const hit=e.target.closest('[data-appid]');if(hit)load(hit.dataset.appid);});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();search.focus();}});
async function load(appid){results.innerHTML='<div class="result">Loading live Steam data…</div>';try{current=await api(`/api/game?appid=${appid}`);render(current);results.innerHTML='';search.value=current.name;}catch(e){results.innerHTML=`<div class="result error">${esc(e.message)}</div>`;}}
function render(g){document.querySelector('#cover-art').style.backgroundImage=`linear-gradient(#0d0e0bbb,#0d0e0b77),url('${g.image}')`;document.querySelector('#cover-title').textContent=g.name.toUpperCase().slice(0,18);document.querySelector('#state-updated').textContent=`LIVE STEAM DATA · ${date(g.updated)}`;document.querySelector('#game-title').textContent=g.name;document.querySelector('#game-meta').textContent=`${g.developers.join(', ')||'Steam'} · ${g.genres.join(' / ')||'Game'} · ${g.platforms.join(' / ')}`;document.querySelector('#verdict').textContent=g.verdict;document.querySelector('#score').textContent=g.score;document.querySelector('#chart-score').textContent=g.score;document.querySelector('#summary').textContent=g.description;document.querySelector('#review-signal').innerHTML=`<b>${g.score}%</b> positive recent reviews`;document.querySelector('#release-signal').innerHTML=`<b>${esc(g.release)}</b> release date`;document.querySelector('#event-grid').innerHTML=g.news.slice(0,3).map(n=>`<article><span class="event-date">${date(n.date).toUpperCase()}</span><h3><a href="${esc(n.url)}" target="_blank" rel="noreferrer">${esc(n.title)}</a></h3><p>${esc(n.summary)}</p><strong class="positive">Official Steam post ↗</strong></article>`).join('')||'<article><span class="event-date">NO RECENT POSTS</span><h3>No Steam announcements found</h3></article>';document.querySelector('#review-grid').innerHTML=g.reviews.slice(0,3).map(r=>`<article class="review"><div class="review-top"><span class="avatar blue">S</span><div><b>Steam player</b><small>${date(r.date)} · ${r.hours}h played</small></div><span class="${r.up?'recommend':'mixed'}">${r.up?'Recommended':'Not recommended'}</span></div><p>“${esc(r.text)}”</p></article>`).join('')||'<article class="review"><p>No recent reviews returned.</p></article>';watch();}
function watch(){const b=document.querySelector('#watch-button'),items=new Set(JSON.parse(localStorage.getItem('gamepulse-watch')||'[]'));b.textContent=items.has(current.appid)?'✓ Watching':'＋ Watch';b.onclick=()=>{items.has(current.appid)?items.delete(current.appid):items.add(current.appid);localStorage.setItem('gamepulse-watch',JSON.stringify([...items]));watch();};}
load(1091500);
