const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),{URL}=require('node:url');
const base=__dirname, port=process.env.PORT||3000;
const send=(res,status,body)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(body));};
const steam=async url=>{const r=await fetch(url,{headers:{'user-agent':'GamePulseMVP/0.1'}});if(!r.ok)throw Error(`Steam returned ${r.status}`);return r.json();};
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
async function search(q){const d=await steam(`https://store.steampowered.com/api/storesearch/?term=${encodeURIComponent(q)}&l=en&cc=us`);return(d.items||[]).slice(0,8).map(x=>({appid:x.id,name:x.name,image:x.tiny_image}));}
async function game(appid){const [details,reviews,news]=await Promise.all([steam(`https://store.steampowered.com/api/appdetails?appids=${appid}&l=en&cc=us`),steam(`https://store.steampowered.com/appreviews/${appid}?json=1&language=english&purchase_type=all&num_per_page=6&filter=recent`),steam(`https://api.steampowered.com/ISteamNews/GetNewsForApp/v2/?appid=${appid}&count=6&maxlength=700`)]);const record=details[appid];if(!record?.success)throw Error('Steam listing unavailable');const g=record.data,q=reviews.query_summary||{},score=q.total_reviews?Math.round(100*q.total_positive/q.total_reviews):50;return{appid:g.steam_appid,name:g.name,image:g.header_image,developers:g.developers||[],genres:(g.genres||[]).map(x=>x.description),platforms:Object.keys(g.platforms||{}).filter(k=>g.platforms[k]),release:g.release_date?.date||'Unknown',description:clean(g.short_description),score,verdict:score>=85?'Play it now':score>=70?'Worth considering':score>=50?'Wait for a sale':'Skip for now',reviewCount:q.total_reviews||0,reviewLabel:q.review_score_desc||'No recent review summary',updated:new Date().toISOString(),reviews:(reviews.reviews||[]).map(x=>({up:x.voted_up,text:clean(x.review).slice(0,320),date:new Date(x.timestamp_created*1000).toISOString(),hours:Math.round((x.author?.playtime_forever||0)/60)})),news:(news.appnews?.newsitems||[]).map(x=>({title:x.title,url:x.url,date:new Date(x.date*1000).toISOString(),summary:clean(x.contents).slice(0,240)}))};}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8'};
http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host}`);try{if(u.pathname==='/api/search'){const q=u.searchParams.get('q')?.trim();return q?.length>1?send(res,200,await search(q)):send(res,400,{error:'Enter at least two characters'});}if(u.pathname==='/api/game'){const id=u.searchParams.get('appid');return /^\d+$/.test(id||'')?send(res,200,await game(id)):send(res,400,{error:'A numeric Steam app ID is required'});}const name=u.pathname==='/'?'index.html':u.pathname.slice(1),file=path.resolve(base,name);if(!file.startsWith(base)||!fs.existsSync(file))return send(res,404,{error:'Not found'});res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res);}catch(e){console.error(e);send(res,502,{error:'Could not retrieve live Steam data. Try again shortly.'});}}).listen(port,()=>console.log(`GamePulse: http://localhost:${port}`));
